### ISSUE TITLE
Document how to retrieve the list of studies that use a particular data dictionary

### ISSUE THREAD

**Issue by gaurav** [HEAL/heal-metadata-schemas#19]
At the moment, the quickest way to download all the data dictionaries from the Platform MDS is by:
1. Accessing the list of all data dictionaries at https://preprod.healdata.org/mds/metadata?_guid_type=data_dictionary&limit=10000
2. Downloading each individual data dictionary by concatenating the identifier to the MDS path (i.e.`https://preprod.healdata.org/mds/metadata/` to `dg.H34L/e4232941-e154-4366-b1e2-603c8514fc35` to get https://preprod.healdata.org/mds/metadata/dg.H34L/e4232941-e154-4366-b1e2-603c8514fc35).

However, this doesn't include the list of studies that use a particular data dictionary. Is there an API query we could use to access this information, e.g. something like `https://preprod.healdata.org/mds/metadata?studies_that_contain_dd=dg.H34L/e4232941-e154-4366-b1e2-603c8514fc35`? If not, would it be possible to include the list of studies in the data dictionary output (e.g. at https://preprod.healdata.org/mds/metadata/dg.H34L/e4232941-e154-4366-b1e2-603c8514fc35)?

If there's a better way to download all the data dictionaries along with their association with studies, please let us know!

**Comment by gaurav** [comment]
> @gaurav Just to follow up on this. I forgot that all the studies are indexed in a database called the "aggregate MDS." One can use the aggregate MDS to get all the study entries in one object with the query below. I'm wondering if we should open an issue for documenting this in the platform documentation repo? Hope this makes your process more efficient!
> https://preprod.healdata.org/mds/aggregate/metadata?limit=10000&offset=0&flatten=true&pagination=false

Thanks, @mbkranz! Someone recently pointed me to another way of getting all the data in a single query, which is by adding `data=true` to the query, e.g. https://preprod.healdata.org/mds/metadata?_guid_type=discovery_metadata&data=true&limit=10000 for studies and then https://preprod.healdata.org/mds/metadata?_guid_type=data_dictionary&data=true&limit=10000 for data dictionaries.

Between all these options, I'm happy to close this issue for now. We can re-open it if we run into any issues with trying to bulk-download data dictionaries as the number of available data dictionaries increase.

**Comment by mbkranz** [comment]
Oh, good to know re: the data param!
