### ISSUE TITLE
Field `module` should be formalized in the specification

### ISSUE THREAD

**Issue by gaurav** [HEAL/heal-metadata-schemas#31]
In looking through the SPRINT data dictionary in the Platform MDS Prod instance (https://healdata.org/mds/metadata/9ca8f3b7-c836-4f98-bd4c-f9d6463c9ddb), we noticed that the `Form Name` field from the SPRINT data dictionary had been stored in the `module` field (e.g. item `11` has a name of `status`, a title of `Post-Baseline Study Status` and a module of `participant_tracking_phi_do_not_share`). This field is not documented in https://github.com/HEAL/heal-metadata-schemas/blob/4de72076cc7485c511b0ba615a5bdafee3a81140/variable-level-metadata-schema/schemas/fields.json, but @suparna-renci and I think that it will be critically important for HEAL Dug users to see which constructs are being measured by a particular study. We think this field should be formally added to the fields list so that we can ensure that this field -- or something like that -- will be included in all future data dictionaries.

**Comment by mbkranz** [comment]
It looks like the above is from an older version? Here are some current (and draft PR)
 
1. Current schemas and dictionaries in `main` branch with `module`:

- current json `fields.json` : https://github.com/HEAL/heal-metadata-schemas/blob/main/variable-level-metadata-schema/schemas/jsonschema/fields.json
- current dictionary source yaml file: https://github.com/HEAL/heal-metadata-schemas/blob/main/variable-level-metadata-schema/schemas/dictionary/fields.yaml

2. Draft PR I am working on

- In this PR, I am intending to improve the documentation annotations in general. Want to add some comments on additional wording and then I'll make into an official PR?

**Comment by gaurav** [comment]
You are correct -- `module` is fully documented in https://github.com/HEAL/heal-metadata-schemas/blob/b4f3619e42610ddd1b490747303d44306b85887d/variable-level-metadata-schema/schemas/jsonschema/fields.json! I'm going to close this issue.

I had a quick look at PR https://github.com/HEAL/heal-metadata-schemas/pull/29 and it looks pretty good to me! I notice there are still references to `cde_id` and `ontology_id` in the model -- I thought we were replacing that with `standardsMappings` and `relatedConcepts`? I would suggest adding some examples to show how `standardsMappings` and `relatedConcepts` are supposed to be used -- these used to be in the `templates/` directory, but it would be better to leave the templates empty as they currently are and make another `examples/` directory for the examples. (If you want to be really finicky about it, you could create `examples/correct` and `examples/incorrect` directories, and then have GitHub Actions set up to make sure that `examples/correct` files pass validation and that `examples/incorrect` files fail validation in predictable ways.)
