### ISSUE TITLE
Change `descriptions` in VLMD to highly recommended

### ISSUE THREAD

**Issue by mbkranz** [HEAL/heal-metadata-schemas#33]
Currently, `description` is required in the VLMD schema for each variable. However, this may be tediuous to fill out all variables (esp as more variables are added).

Proposal: delete "required" and change to "highly recommended".

This will make "name" the only `required` property.

**Comment by mbkranz** [comment]
Ok with this? Came up in discussion with Phil today
@gaurav 
@pschumm

**Comment by gaurav** [comment]
I’m okay with this — I agree that making them required will cause people to give up or do something useless like copy the field name into the description field. It might be worth running this past the Data Task Force this Wednesday just to make sure we’re not missing anything.

**Comment by mbkranz** [comment]
Closing out -- at data task force decided to keep required
